name: Deploy Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run the bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        PORT: 3000
      run: |
        node index.js

    - name: Send Telegram notification
      uses: appleboy/telegram-action@v0.1.0
      with:
        to: "@hoangtuan15326"
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: "Telegram bot is running on GitHub Actions"
